---
author: 'Yoshinori Matsunobu <Yoshinori.Matsunobu@gmail.com>'
distribution_type: module
generated_by: 'Module::Install version 0.67'
license: 'GPL v2'
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: mha4mysql-node
no_index:
  directory:
    - inc
    - t
requires:
  DBD::mysql: 0
  DBI: 0
version: 0.55
